[package]
name = "reverse-task"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
env_logger = "0.11.8"
hex = "0.4.3"
hex-literal = "1.0.0"
log = "0.4.28"
nanoid = "0.4.0"
sha3 = "0.10.8"
